sudo: required
services:
  - docker
before_install:
  - docker build -t faisaldev79/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true faisaldev79/react-test npm test
after_success:
  - docker build -t faisaldev79/multi-client ./client
  - docker build -t faisaldev79/multi-nginx ./nginx
  - docker build -t faisaldev79/multi-server ./server
  - docker build -t faisaldev79/multi-worker ./worker
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push faisaldev79/multi-client
  - docker push faisaldev79/multi-nginx
  - docker push faisaldev79/multi-server
  - docker push faisaldev79/multi-worker
deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-container'
  env: 'Multicontainer-env'
  bucket_name: 'elasticbeanstalk-us-east-2-109831127073'
  bucket_path: 'multi-container'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
